// <auto-generated />
using System;
using FitTinaV2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitTinaV2.Migrations
{
    [DbContext(typeof(FitTinaDbContext))]
    [Migration("20201207064408_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("FitTina.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentRequired")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("ExerciseID");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseID = 1,
                            EquipmentRequired = "Dumbbells",
                            Name = "Alternating Bicep Curl",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=xxgxVU1NsNc"
                        },
                        new
                        {
                            ExerciseID = 2,
                            EquipmentRequired = "Dumbbells",
                            Name = "Front Delt Raise",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=2aoEWSvPBeI"
                        },
                        new
                        {
                            ExerciseID = 3,
                            EquipmentRequired = "Dumbbells",
                            Name = "Lateral Delt Raise",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=Q4SMoasiMI0"
                        },
                        new
                        {
                            ExerciseID = 4,
                            EquipmentRequired = "Dumbbells",
                            Name = "Rear Delt Raise",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=p1yQnTNE808"
                        },
                        new
                        {
                            ExerciseID = 5,
                            EquipmentRequired = "Dumbbells",
                            Name = "Bent Over Row",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=ZXpZu_fmheU"
                        },
                        new
                        {
                            ExerciseID = 6,
                            EquipmentRequired = "Dumbbells",
                            Name = "Tricep Extension",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=nRiJVZDpdL0"
                        },
                        new
                        {
                            ExerciseID = 7,
                            EquipmentRequired = "Dumbbells",
                            Name = "Chest Press",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=jRUC6IVav30"
                        },
                        new
                        {
                            ExerciseID = 8,
                            EquipmentRequired = "Dumbbells",
                            Name = "Single Arm Chest Press",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=6tbjm5FjhB0"
                        },
                        new
                        {
                            ExerciseID = 9,
                            EquipmentRequired = "Dumbbells",
                            Name = "Chest Fly",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=y_Z2LftZDvk"
                        },
                        new
                        {
                            ExerciseID = 10,
                            EquipmentRequired = "Dumbbells",
                            Name = "Military Press",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=B-aVuyhvLHU"
                        },
                        new
                        {
                            ExerciseID = 11,
                            EquipmentRequired = "Dumbbells",
                            Name = "Hammer Curl",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=P5sXHLmXmBM"
                        },
                        new
                        {
                            ExerciseID = 12,
                            EquipmentRequired = "Dumbbells",
                            Name = "Rear Delt Fly",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=dA4iqyTgx5I"
                        },
                        new
                        {
                            ExerciseID = 13,
                            EquipmentRequired = "Dumbbells",
                            Name = "Tricep Kickback",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=ZO81bExngMI"
                        },
                        new
                        {
                            ExerciseID = 14,
                            EquipmentRequired = "Dumbbells",
                            Name = "Single Arm Kneeling Row",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=l_qeCPJMU9o"
                        },
                        new
                        {
                            ExerciseID = 15,
                            EquipmentRequired = "Dumbbells",
                            Name = "Seesaw Press",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=jn2aqML1FIs"
                        },
                        new
                        {
                            ExerciseID = 16,
                            EquipmentRequired = "Dumbbells",
                            Name = "Hang Clean",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=hFXPxXkYr_o"
                        },
                        new
                        {
                            ExerciseID = 17,
                            EquipmentRequired = "Dumbbells",
                            Name = "Single Arm Overhead Press",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=NVnyDQqmhPo"
                        },
                        new
                        {
                            ExerciseID = 18,
                            EquipmentRequired = "Dumbbells",
                            Name = "Bus Driver",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=25g1bRCOoHc"
                        },
                        new
                        {
                            ExerciseID = 19,
                            EquipmentRequired = "Bodyweight",
                            Name = "Push-Ups",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=IODxDxX7oi4"
                        },
                        new
                        {
                            ExerciseID = 20,
                            EquipmentRequired = "Bodyweight",
                            Name = "Bench Dips",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=IODxDxX7oi4"
                        },
                        new
                        {
                            ExerciseID = 21,
                            EquipmentRequired = "Bodyweight",
                            Name = "Superman Hold",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=cc6UVRS7PW4"
                        },
                        new
                        {
                            ExerciseID = 22,
                            EquipmentRequired = "Bodyweight",
                            Name = "Triangle Push-Ups",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=hfIQ5V4Tcgo"
                        },
                        new
                        {
                            ExerciseID = 23,
                            EquipmentRequired = "Bodyweight",
                            Name = "Incline Push-Ups",
                            Type = "Upper Body",
                            VideoUrl = "https://www.youtube.com/watch?v=Gvm5Q29UHbk"
                        },
                        new
                        {
                            ExerciseID = 24,
                            EquipmentRequired = "Dumbbells",
                            Name = "Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=v_c67Omje48"
                        },
                        new
                        {
                            ExerciseID = 25,
                            EquipmentRequired = "Dumbbells",
                            Name = "Pulse Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=j4yJvxvlqXw"
                        },
                        new
                        {
                            ExerciseID = 26,
                            EquipmentRequired = "Dumbbells",
                            Name = "Goblet Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=MJao9o7ROs0"
                        },
                        new
                        {
                            ExerciseID = 27,
                            EquipmentRequired = "Dumbbells",
                            Name = "Reverse Lunge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=ZK-O_aS3GdY"
                        },
                        new
                        {
                            ExerciseID = 28,
                            EquipmentRequired = "Dumbbells",
                            Name = "Romanian Deadlfit",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=UsOjCcxSJaI"
                        },
                        new
                        {
                            ExerciseID = 29,
                            EquipmentRequired = "Dumbbells",
                            Name = "Bulgarian Split Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=TwsAe8xrnqE"
                        },
                        new
                        {
                            ExerciseID = 30,
                            EquipmentRequired = "Dumbbells",
                            Name = "Weighted Glute Bridge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=iiu7ArCUjF8"
                        },
                        new
                        {
                            ExerciseID = 31,
                            EquipmentRequired = "Dumbbells",
                            Name = "Hip Thrust",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=1Yezfp-YWc8"
                        },
                        new
                        {
                            ExerciseID = 32,
                            EquipmentRequired = "Dumbbells",
                            Name = "Sumo Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=3eMBG2-lD4I"
                        },
                        new
                        {
                            ExerciseID = 33,
                            EquipmentRequired = "Dumbbells",
                            Name = "Walking Lunges",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=SniKHGKDJyU"
                        },
                        new
                        {
                            ExerciseID = 34,
                            EquipmentRequired = "Dumbbells",
                            Name = "Single Leg RDL",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=IlOrGu1qzWs"
                        },
                        new
                        {
                            ExerciseID = 35,
                            EquipmentRequired = "Dumbbells",
                            Name = "Standing Calf Raise",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=wxwY7GXxL4k"
                        },
                        new
                        {
                            ExerciseID = 36,
                            EquipmentRequired = "Dumbbells",
                            Name = "Curtsy Lunge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=Mqkcr0LeNR4"
                        },
                        new
                        {
                            ExerciseID = 37,
                            EquipmentRequired = "Dumbbells",
                            Name = "Deadlift",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=Ipi8_vz8_z0"
                        },
                        new
                        {
                            ExerciseID = 38,
                            EquipmentRequired = "Dumbbells",
                            Name = "Offset Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=PsCuU0Fs49I"
                        },
                        new
                        {
                            ExerciseID = 39,
                            EquipmentRequired = "Dumbbells",
                            Name = "Lateral Lunge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=ktdMS7WBwck"
                        },
                        new
                        {
                            ExerciseID = 40,
                            EquipmentRequired = "Dumbbells",
                            Name = "Hamstring Curl",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=cSzoVHHnuu0"
                        },
                        new
                        {
                            ExerciseID = 41,
                            EquipmentRequired = "Dumbbells",
                            Name = "3D Lunge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=p2rVtx5nCL8"
                        },
                        new
                        {
                            ExerciseID = 42,
                            EquipmentRequired = "Bodyweight",
                            Name = "Air Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=jcyoiT98jdk"
                        },
                        new
                        {
                            ExerciseID = 43,
                            EquipmentRequired = "Bodyweight",
                            Name = "Reverse Air Lunge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=tpVhJNQURk4"
                        },
                        new
                        {
                            ExerciseID = 44,
                            EquipmentRequired = "Bodyweight",
                            Name = "Lateral Air Lunge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=gwWv7aPcD88"
                        },
                        new
                        {
                            ExerciseID = 45,
                            EquipmentRequired = "Bodyweight",
                            Name = "Bulgarian Air Split Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=aSJbKnDRIiQ"
                        },
                        new
                        {
                            ExerciseID = 46,
                            EquipmentRequired = "Bodyweight",
                            Name = "Single Leg Glute Bridge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=Y-6Gonx2Wpo"
                        },
                        new
                        {
                            ExerciseID = 47,
                            EquipmentRequired = "Bodyweight",
                            Name = "Glute Bridge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=9NkNgFc_-Ys"
                        },
                        new
                        {
                            ExerciseID = 48,
                            EquipmentRequired = "Bodyweight",
                            Name = "Pistol Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=vq5-vdgJc0I"
                        },
                        new
                        {
                            ExerciseID = 49,
                            EquipmentRequired = "Bodyweight",
                            Name = "Glute Kickbacks",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=BNDw4ciQoQI"
                        },
                        new
                        {
                            ExerciseID = 50,
                            EquipmentRequired = "Bodyweight",
                            Name = "Sumo Air Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=mhcEWu-0pzs"
                        },
                        new
                        {
                            ExerciseID = 51,
                            EquipmentRequired = "Bodyweight",
                            Name = "Walking Air Lunges",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=r49nFlyDvTc"
                        },
                        new
                        {
                            ExerciseID = 52,
                            EquipmentRequired = "Bodyweight",
                            Name = "Pulse Air Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=N4fzbBv4BFI"
                        },
                        new
                        {
                            ExerciseID = 53,
                            EquipmentRequired = "Bodyweight",
                            Name = "Single Leg Air RDL",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=2SoSzhDkoXA"
                        },
                        new
                        {
                            ExerciseID = 54,
                            EquipmentRequired = "Bodyweight",
                            Name = "Air Curtsy Lunge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=4nUxVn0K6d4"
                        },
                        new
                        {
                            ExerciseID = 55,
                            EquipmentRequired = "Bodyweight",
                            Name = "Lateral Squat Walk",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=NK57EZP_v34"
                        },
                        new
                        {
                            ExerciseID = 56,
                            EquipmentRequired = "Bodyweight",
                            Name = "Arms-Overhead Air Squat",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=02uirDvXUUo"
                        },
                        new
                        {
                            ExerciseID = 57,
                            EquipmentRequired = "Bodyweight",
                            Name = "Side Leg Raise",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=jgh6sGwtTwk"
                        },
                        new
                        {
                            ExerciseID = 58,
                            EquipmentRequired = "Bodyweight",
                            Name = "Clamshell",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=EG5_gXcfozw"
                        },
                        new
                        {
                            ExerciseID = 59,
                            EquipmentRequired = "Bodyweight",
                            Name = "3D Air Lunge",
                            Type = "Lower Body",
                            VideoUrl = "https://www.youtube.com/watch?v=p2rVtx5nCL8"
                        },
                        new
                        {
                            ExerciseID = 60,
                            EquipmentRequired = "Bodyweight",
                            Name = "Russian Twists",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=JyUqwkVpsi8"
                        },
                        new
                        {
                            ExerciseID = 61,
                            EquipmentRequired = "Bodyweight",
                            Name = "Lying Leg Raises",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=UvcTNVbjTYo"
                        },
                        new
                        {
                            ExerciseID = 62,
                            EquipmentRequired = "Bodyweight",
                            Name = "Plank",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=B296mZDhrP4"
                        },
                        new
                        {
                            ExerciseID = 63,
                            EquipmentRequired = "Bodyweight",
                            Name = "Side Plank",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=IkMmABQ9SkM"
                        },
                        new
                        {
                            ExerciseID = 64,
                            EquipmentRequired = "Bodyweight",
                            Name = "Forearm Plank Jacks",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=UmbhcRt-s58"
                        },
                        new
                        {
                            ExerciseID = 65,
                            EquipmentRequired = "Bodyweight",
                            Name = "Spider Crawl",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=_K7rv_vFOWM"
                        },
                        new
                        {
                            ExerciseID = 66,
                            EquipmentRequired = "Bodyweight",
                            Name = "V Sit-Up",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=WTmnP0xIdq8"
                        },
                        new
                        {
                            ExerciseID = 67,
                            EquipmentRequired = "Bodyweight",
                            Name = "Reverse Crunch",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=YDvaOlhaA1U"
                        },
                        new
                        {
                            ExerciseID = 68,
                            EquipmentRequired = "Bodyweight",
                            Name = "Sit-Ups",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=1fbU_MkV7NE"
                        },
                        new
                        {
                            ExerciseID = 69,
                            EquipmentRequired = "Bodyweight",
                            Name = "Mountain Climbers",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=cnyTQDSE884"
                        },
                        new
                        {
                            ExerciseID = 70,
                            EquipmentRequired = "Bodyweight",
                            Name = "Hip Dip Plank",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=XAT8SDAj5EM"
                        },
                        new
                        {
                            ExerciseID = 71,
                            EquipmentRequired = "Bodyweight",
                            Name = "Bicycle Crunches",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=1we3bh9uhqY"
                        },
                        new
                        {
                            ExerciseID = 72,
                            EquipmentRequired = "Bodyweight",
                            Name = "Walkouts",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=R6SMJ-TzgZo"
                        },
                        new
                        {
                            ExerciseID = 73,
                            EquipmentRequired = "Bodyweight",
                            Name = "Plank with Shoulder Taps",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=ztpXZm7Dv80"
                        },
                        new
                        {
                            ExerciseID = 74,
                            EquipmentRequired = "Bodyweight",
                            Name = "Jack Knife Sit-Ups",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=GI4S_zkJJkM"
                        },
                        new
                        {
                            ExerciseID = 75,
                            EquipmentRequired = "Bodyweight",
                            Name = "Standing Oblique Crunch",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=YH_2t6Hh7GQ"
                        },
                        new
                        {
                            ExerciseID = 76,
                            EquipmentRequired = "Bodyweight",
                            Name = "Flutter Kicks",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=ZB1SwBRVLCc"
                        },
                        new
                        {
                            ExerciseID = 77,
                            EquipmentRequired = "Bodyweight",
                            Name = "Butterfly Sit-Ups",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=hdXsuDt2PKE"
                        },
                        new
                        {
                            ExerciseID = 78,
                            EquipmentRequired = "Bodyweight",
                            Name = "Bird Dog",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=zs82fV88_lM"
                        },
                        new
                        {
                            ExerciseID = 79,
                            EquipmentRequired = "Bodyweight",
                            Name = "Cross-Body Mountain Climber",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=luRruRjECm8"
                        },
                        new
                        {
                            ExerciseID = 80,
                            EquipmentRequired = "Bodyweight",
                            Name = "Floor Toe Taps",
                            Type = "Core",
                            VideoUrl = "https://www.youtube.com/watch?v=Ml2xTP45jVQ"
                        },
                        new
                        {
                            ExerciseID = 81,
                            EquipmentRequired = "Dumbbells",
                            Name = "Kettlebell Swing",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=YSxHifyI6s8"
                        },
                        new
                        {
                            ExerciseID = 82,
                            EquipmentRequired = "Dumbbells",
                            Name = "Push-Up to Row",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=NW7d5SLOtiI"
                        },
                        new
                        {
                            ExerciseID = 83,
                            EquipmentRequired = "Dumbbells",
                            Name = "Dumbbell Burpee",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=vxZM3dR9deg"
                        },
                        new
                        {
                            ExerciseID = 84,
                            EquipmentRequired = "Dumbbells",
                            Name = "Alternating Dumbbell Snatch",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=OktkfRlGcns"
                        },
                        new
                        {
                            ExerciseID = 85,
                            EquipmentRequired = "Dumbbells",
                            Name = "Lunge to Curl",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=fIvr9ootgos"
                        },
                        new
                        {
                            ExerciseID = 86,
                            EquipmentRequired = "Dumbbells",
                            Name = "Squat Press",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=y29Cs067sD8"
                        },
                        new
                        {
                            ExerciseID = 87,
                            EquipmentRequired = "Dumbbells",
                            Name = "Clean and Press",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=4MKfeQDkkNY"
                        },
                        new
                        {
                            ExerciseID = 88,
                            EquipmentRequired = "Dumbbells",
                            Name = "Renegade Row",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=LccyTxiUrhg"
                        },
                        new
                        {
                            ExerciseID = 89,
                            EquipmentRequired = "Dumbbells",
                            Name = "Step-Up to Press",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=v-WOS5l81SY"
                        },
                        new
                        {
                            ExerciseID = 90,
                            EquipmentRequired = "Dumbbells",
                            Name = "Loaded Carry",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=0LVcc8620qo"
                        },
                        new
                        {
                            ExerciseID = 91,
                            EquipmentRequired = "Dumbbells",
                            Name = "Suitcase Carry",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=qp4PeLphg6M"
                        },
                        new
                        {
                            ExerciseID = 92,
                            EquipmentRequired = "Dumbbells",
                            Name = "Kneeling Wood Chop",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=2lpkNhQR_Aw"
                        },
                        new
                        {
                            ExerciseID = 93,
                            EquipmentRequired = "Dumbbells",
                            Name = "Reverse Lunge to Single-Arm Press",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=OEozeabd-oA"
                        },
                        new
                        {
                            ExerciseID = 94,
                            EquipmentRequired = "Bodyweight",
                            Name = "T Push-Ups",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=vKaLCCNxMho"
                        },
                        new
                        {
                            ExerciseID = 95,
                            EquipmentRequired = "Bodyweight",
                            Name = "Fire Hydrant",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=CAZZz7uP-Ok"
                        },
                        new
                        {
                            ExerciseID = 96,
                            EquipmentRequired = "Bodyweight",
                            Name = "Wall Walk",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=cjY1xl-ddwo"
                        },
                        new
                        {
                            ExerciseID = 97,
                            EquipmentRequired = "Bodyweight",
                            Name = "Single Leg Side Plank",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=lFzJQXiljF4"
                        },
                        new
                        {
                            ExerciseID = 98,
                            EquipmentRequired = "Bodyweight",
                            Name = "T-Rotation",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=yaM8hDcSyH4"
                        },
                        new
                        {
                            ExerciseID = 99,
                            EquipmentRequired = "Bodyweight",
                            Name = "Bear Crunch",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=YMj_2GYROvg"
                        },
                        new
                        {
                            ExerciseID = 100,
                            EquipmentRequired = "Bodyweight",
                            Name = "Spiderman Push-Up",
                            Type = "Compound",
                            VideoUrl = "https://www.youtube.com/watch?v=vo_Dvi8ktIE"
                        },
                        new
                        {
                            ExerciseID = 101,
                            EquipmentRequired = "Bodyweight",
                            Name = "Jump Squat",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=J6Y520KkwOA"
                        },
                        new
                        {
                            ExerciseID = 102,
                            EquipmentRequired = "Bodyweight",
                            Name = "Jump Squat with Tuck",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=lh5W0vzT4oE"
                        },
                        new
                        {
                            ExerciseID = 103,
                            EquipmentRequired = "Bodyweight",
                            Name = "Alternating Split Squat Jump",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=ZiupDCper-M"
                        },
                        new
                        {
                            ExerciseID = 104,
                            EquipmentRequired = "Bodyweight",
                            Name = "Jumping Jacks",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=iRVzVa0GSYY"
                        },
                        new
                        {
                            ExerciseID = 105,
                            EquipmentRequired = "Bodyweight",
                            Name = "High Knees",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=oDdkytliOqE"
                        },
                        new
                        {
                            ExerciseID = 106,
                            EquipmentRequired = "Bodyweight",
                            Name = "Sprints",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=3nbjhpcZ9_g"
                        },
                        new
                        {
                            ExerciseID = 107,
                            EquipmentRequired = "Bodyweight",
                            Name = "Burpees",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=tJrdJBWBu08"
                        },
                        new
                        {
                            ExerciseID = 108,
                            EquipmentRequired = "Bodyweight",
                            Name = "Step-Ups with Knee Raise",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=df-HaATHVnQ"
                        },
                        new
                        {
                            ExerciseID = 109,
                            EquipmentRequired = "Bodyweight",
                            Name = "Standing Long Jump",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=yFdHdQ_fXSo"
                        },
                        new
                        {
                            ExerciseID = 110,
                            EquipmentRequired = "Bodyweight",
                            Name = "Toe Taps",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=l5V0BJJFNoY"
                        },
                        new
                        {
                            ExerciseID = 111,
                            EquipmentRequired = "Bodyweight",
                            Name = "Ski Jump",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=yk7yXdzabxY"
                        },
                        new
                        {
                            ExerciseID = 112,
                            EquipmentRequired = "Bodyweight",
                            Name = "Squat Jacks",
                            Type = "Cardio",
                            VideoUrl = "https://www.youtube.com/watch?v=LK3jSsdQ7M4"
                        });
                });

            modelBuilder.Entity("FitTina.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentPref")
                        .HasColumnType("TEXT");

                    b.Property<string>("FitnessGoal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitTinaV2.Models.Workout", b =>
                {
                    b.Property<int>("WorkoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Exercise1ExerciseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Exercise2ExerciseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Exercise3ExerciseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Exercise4ExerciseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Exercise5ExerciseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Exercise6ExerciseID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkoutID");

                    b.HasIndex("Exercise1ExerciseID");

                    b.HasIndex("Exercise2ExerciseID");

                    b.HasIndex("Exercise3ExerciseID");

                    b.HasIndex("Exercise4ExerciseID");

                    b.HasIndex("Exercise5ExerciseID");

                    b.HasIndex("Exercise6ExerciseID");

                    b.HasIndex("UserID");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitTinaV2.Models.Workout", b =>
                {
                    b.HasOne("FitTina.Models.Exercise", "Exercise1")
                        .WithMany()
                        .HasForeignKey("Exercise1ExerciseID");

                    b.HasOne("FitTina.Models.Exercise", "Exercise2")
                        .WithMany()
                        .HasForeignKey("Exercise2ExerciseID");

                    b.HasOne("FitTina.Models.Exercise", "Exercise3")
                        .WithMany()
                        .HasForeignKey("Exercise3ExerciseID");

                    b.HasOne("FitTina.Models.Exercise", "Exercise4")
                        .WithMany()
                        .HasForeignKey("Exercise4ExerciseID");

                    b.HasOne("FitTina.Models.Exercise", "Exercise5")
                        .WithMany()
                        .HasForeignKey("Exercise5ExerciseID");

                    b.HasOne("FitTina.Models.Exercise", "Exercise6")
                        .WithMany()
                        .HasForeignKey("Exercise6ExerciseID");

                    b.HasOne("FitTina.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
